name: Java CI 

on:
  push:
    branches: [ "main" ]

jobs:
  compile-job:
    runs-on: ubuntu-latest

    steps:
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Running Test.java File
      run: java Test.java

    #     cache: maven
    # - name: Build with Maven
    #   run: mvn -B package --file pom.xml

