name: Spring Boot CI/CD 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Test
      run: mvn test
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v5
      if: always() # always run even if tests fail
      with:
        report_paths: '**/target/surefire-reports/TEST-*.xml'
        detailed_summary: true
        include_passed: true
        fail_on_failure: false

  security-check:
      needs: [build]
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4
        - name: Trivy Installation
          run: |
            sudo apt-get install -y wget apt-transport-https gnupg lsb-release
            wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
            echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
            sudo apt-get update -y
            sudo apt-get install -y trivy

